# bargaining
payoff_ranking:
  label: payoff ranking
  file: matches_ranking.rmd
evolution:
  label: evolution
  file: evolution.rmd
diag_payoffs_over_time:
  label: against itself
  file: diag_payoffs_over_time.rmd
payoffs_over_time:
  label: payoff over time
  file: payoffs_over_time.rmd
duels_over_time:
  label: duels over time
  file: duels_over_time.rmd
duels_diff_over_time:
  label: duels diff over time
  file: duels_diff_over_time.rmd
duel_stats:
  label: duel stats
  file: payoff_diff_ranking.rmd
payoff_matrix:
  label: payoff matrix
  file: matches_payoff_matrix.rmd
duels_plot:
  label: duels plot
  file: matches_duels_plot.rmd
strat_stats:
  label: strat stats
  file: strat_indicators.rmd
strategies:
  label: strategies
  file: show_strat_code.rmd